# Tensor Flow

In [1]:
import tensorflow as tf

C:\Users\taina\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\taina\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\taina\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\taina\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passi

In [2]:
tf.__version__

'1.14.0'

In [3]:
hello = tf.constant('Hello TensorFlow!')

In [4]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [5]:
sess = tf.Session()

In [6]:
print(sess)

In [7]:
print(sess.run(hello))

b'Hello TensorFlow!'


# Soma

In [8]:
a = tf.constant(9)
b = tf.constant(10)

In [9]:
a

<tf.Tensor 'Const_1:0' shape=() dtype=int32>

In [10]:
total = a + b

In [11]:
# aqui estamos apenas criando o grafo e adicionando uma operação de adição 
# por isso a operação matematica nao é computada
# essa computação só sera realizada quando fazermos uma session para rodar o grafo
total

<tf.Tensor 'add:0' shape=() dtype=int32>

In [12]:
with tf.Session() as sess:
    print("A soma dos tensores é: %.2f" % sess.run(total))

A soma dos tensores é: 19.00


In [13]:
# Criando os nodes no grafo computacional
node1 = tf.constant(5, dtype=tf.int32)
node2 = tf.constant(9, dtype=tf.int32)
node3 = tf.add(node1, node2)

# Cria a sessão TF
sess = tf.Session()
 
# Executa o grafo
print("\nA soma do node1 com o node2 é:", sess.run(node3))
 
# Fecha a sessão
sess.close()


A soma do node1 com o node2 é: 14


# Subtração

In [14]:
# Tensores randômicos
#distribuição normal
a1 = tf.random_normal([3], 2.0)
#distribuiçãou uniforme
b1 = tf.random_uniform([3], 1.0, 4.0)

In [33]:
a1

<tf.Tensor 'random_normal:0' shape=(3,) dtype=float32>

In [34]:
b1

<tf.Tensor 'random_uniform:0' shape=(3,) dtype=float32>

In [46]:
c1 = tf.subtract(a1,b1)

In [47]:
c1

<tf.Tensor 'Sub_7:0' shape=(3,) dtype=float32>

In [48]:
sess = tf.Session()

print("Sub = ", sess.run(c1))

Sub =  [ 0.10456467 -1.7923863   1.0066509 ]


# Divisão

In [51]:
a = tf.constant(21, dtype = tf.int32) 
b = tf.constant(7, dtype = tf.int32)

div = tf.div(a, b)

sess1 = tf.Session()

print("Resultado da divisão é %d." % sess1.run(div))

Resultado da divisão é 3.


# Multiplicação

In [52]:
# Criando tensores
# dados de entrada
tensor_a = tf.constant([[4., 2.]])
# pesos
tensor_b = tf.constant([[3.],[7.]])

In [53]:
tensor_a

<tf.Tensor 'Const_21:0' shape=(1, 2) dtype=float32>

In [54]:
tensor_b

<tf.Tensor 'Const_22:0' shape=(2, 1) dtype=float32>

In [55]:
# Multiplicação
# tf.multiply(X, Y) executa multiplicação element-wise: retorna um tensor do mesmo tipo de x (aqui tensor_a)
# https://www.tensorflow.org/api_docs/python/tf/multiply
prod = tf.multiply(tensor_a, tensor_b)

In [56]:
# Executa a sessão
with tf.Session() as sess:
    print('\ntensor_a: \n', sess.run(tensor_a))
    print('\ntensor_b: \n', sess.run(tensor_b))
    print('\nProduto Element-wise Entre os Tensores: \n', sess.run(prod))


tensor_a: 
 [[4. 2.]]

tensor_b: 
 [[3.]
 [7.]]

Produto Element-wise Entre os Tensores: 
 [[12.  6.]
 [28. 14.]]


In [57]:
# Outro exemplo de Multiplicação de Matrizes
mat_a = tf.constant([[2, 3], [9, 2], [4, 5]])
mat_b = tf.constant([[6, 4, 5], [3, 7, 2]])

In [58]:
mat_a

<tf.Tensor 'Const_23:0' shape=(3, 2) dtype=int32>

In [59]:
mat_b

<tf.Tensor 'Const_24:0' shape=(2, 3) dtype=int32>

In [60]:
# Multiplicação
# tf.matmul(X, Y) executa multiplicação entre matrizes: a multiplicação normal
# https://www.tensorflow.org/api_docs/python/tf/matmul
mat_prod = tf.matmul(mat_a, mat_b)

In [61]:
# Executa a sessão
with tf.Session() as sess:
    print('\nTensor mat_a: \n', sess.run(mat_a))
    print('\nTensor mat_b: \n', sess.run(mat_b))
    print('\nProduto Element-wise Entre os Tensores (Matrizes): \n', sess.run(mat_prod))


Tensor mat_a: 
 [[2 3]
 [9 2]
 [4 5]]

Tensor mat_b: 
 [[6 4 5]
 [3 7 2]]

Produto Element-wise Entre os Tensores (Matrizes): 
 [[21 29 16]
 [60 50 49]
 [39 51 30]]


In [63]:
# usando multiply numa matriz 2x2

tensor_a = tf.constant([[4., 2.], [5., 6.]])
# pesos
tensor_b = tf.constant([[3., 1.],[7.,1.]])

print(tensor_a)
print(tensor_b)

prod = tf.multiply(tensor_a, tensor_b)

with tf.Session() as sess:
    print('\ntensor_a: \n', sess.run(tensor_a))
    print('\ntensor_b: \n', sess.run(tensor_b))
    print('\nProduto Element-wise Entre os Tensores: \n', sess.run(prod))


Tensor("Const_27:0", shape=(2, 2), dtype=float32)
Tensor("Const_28:0", shape=(2, 2), dtype=float32)

tensor_a: 
 [[4. 2.]
 [5. 6.]]

tensor_b: 
 [[3. 1.]
 [7. 1.]]

Produto Element-wise Entre os Tensores: 
 [[12.  2.]
 [35.  6.]]


In [64]:
# usando matmul numa matriz 2x2

tensor_a = tf.constant([[4., 2.], [5., 6.]])
# pesos
tensor_b = tf.constant([[3., 1.],[7.,1.]])

print(tensor_a)
print(tensor_b)

prod = tf.matmul(tensor_a, tensor_b)

with tf.Session() as sess:
    print('\ntensor_a: \n', sess.run(tensor_a))
    print('\ntensor_b: \n', sess.run(tensor_b))
    print('\nProduto Element-wise Entre os Tensores: \n', sess.run(prod))

Tensor("Const_29:0", shape=(2, 2), dtype=float32)
Tensor("Const_30:0", shape=(2, 2), dtype=float32)

tensor_a: 
 [[4. 2.]
 [5. 6.]]

tensor_b: 
 [[3. 1.]
 [7. 1.]]

Produto Element-wise Entre os Tensores: 
 [[26.  6.]
 [57. 11.]]


In [ ]:
# Pode-se notar que a função multiply é diferente da função matmul porque a multiply realiza a multiplicação escalar
# (multiplica um elemento por o seu correspondete) e não a multiplicação matricial (que multiplica linhas e colunas).

# Variáveis

In [65]:
# Import
import tensorflow as tf
 
# Criando uma variavel chamada node no grafo computacional
# Cria uma variavel com tensor pupulado com zeros e de dimensões 2x2
node = tf.Variable(tf.zeros([2,2]))
 
# Executando o grafo computacional
with tf.Session() as sess:
 
    # Inicializando as variábeis - Sempre devem ser inicializadas
    sess.run(tf.global_variables_initializer())
 
    # Avaliando o node
    print("\nTensor Original:\n", sess.run(node))
 
    # Adição element-wise no tensor: Pega o node e soma ele a outro tensor (que é um tensor 2x2 preenchido com 1)
    node = node.assign(node + tf.ones([2,2]))
 
    # Avaliando o node novamente
    print("\nTensor depois da adição:\n", sess.run(node))


Tensor Original:
 [[0. 0.]
 [0. 0.]]

Tensor depois da adição:
 [[1. 1.]
 [1. 1.]]


# Placeholders

In [66]:
# Import
import tensorflow as tf
 
# Criando nodes no Grafo Computacional
# Ele irá reservar na memoria uma area com o shape 3x1/1x3 e do tipo int com o nome a/b
a = tf.placeholder(tf.int32, shape=(3,1))
b = tf.placeholder(tf.int32, shape=(1,3))
c = tf.matmul(a,b)
 
# Executando o Grafo Computacional
with tf.Session() as sess:
    # feed_dict: dicionario de alimentação que serve para alimentar os placeholders 
    print(sess.run(c, feed_dict={a:[[3],[2],[1]], b:[[1,2,3]]}))

[[3 6 9]
 [2 4 6]
 [1 2 3]]
